#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def clusterissuer():
---
apiVersion: v1
kind: Secret
metadata:
  name: google-dns-client-secret
  namespace: cert-manager
stringData:
  credentials.json: #@ data.values.google.dns.config
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-contour-cluster-issuer
spec:
  acme:
    email: #@ data.values.tap.credentials.tanzuNet.username
    privateKeySecretRef:
      name: acme-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudDNS:
          project: #@ data.values.google.dns.project_id
          serviceAccountSecretRef:
            name: google-dns-client-secret
            key: credentials.json
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: certmanager-issuer-overlay
  namespace: #@ data.values.certmanager.namespace
  annotations:
    kapp.k14s.io/change-rule: "delete after deleting tap"
stringData:
  othersecret.yaml: #@ yaml.encode(clusterissuer())