#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: rabbitmq
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: rabbitmq-repo
spec:
  fetch:
    imgpkgBundle:
      image: #@ "{}/p-rabbitmq-for-kubernetes/tanzu-rabbitmq-package-repo:{}".format(data.values.tap.credentials.tanzuNet.host, data.values.rabbitmq_repo.version)
      secretRef:
        name: tap-registry
