
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
#@ def config():
---

namespace: #@ data.values.external_dns.target_namespace

deployment:
  args:
    - --metrics-address=:7979 #! ensures external dns exposes metrics
    - --source=service
    - --source=ingress
    - --source=contour-httpproxy
    - --policy=upsert-only
    - --provider=google
    - --policy=upsert-only #! would prevent ExternalDNS from deleting any records, omit to enable full synchronization
    - #@ "--google-project=" + data.values.google.dns.project_id
    - --registry=txt
  env:
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: /etc/secrets/service-account/credentials.json
  volumeMounts:
  - name: google-service-account
    mountPath: /etc/secrets/service-account/
  volumes:
  - name: google-service-account
    secret:
      secretName: gcloud-service-account-credentials
      items:
      - key: credentials.json
        path: credentials.json
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-values
  namespace: #@ data.values.external_dns.namespace
  annotations:
    kapp.k14s.io/change-rule: "delete after deleting external-dns"

type: Opaque
stringData:
  values.yml: #@ yaml.encode(config())
