
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def googlednssecret():
---
apiVersion: v1
kind: Secret
metadata:
  name: gcloud-service-account-credentials
  namespace: tanzu-system-service-discovery
stringData:
  credentials.json: #@ data.values.google.dns.config
#@ end

---
apiVersion: v1
kind: Secret
metadata:
  name: google-dns-secret-overlay
  namespace: #@ data.values.external_dns.namespace
  annotations:
    kapp.k14s.io/change-rule: "delete after deleting tap"
stringData:
  othersecret.yaml: #@ yaml.encode(googlednssecret())