#@ load("@ytt:data", "data")

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: postgres-as-a-service
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: postgres-as-a-service
    kapp.k14s.io/change-rule: "upsert after upserting tap"
spec:
  serviceAccountName: tap-install-gitops-sa
  syncPeriod: 1m
  fetch:
  - git:
      url: #@ data.values.git.url
      ref: #@ data.values.git.ref
      secretRef:
        name: git-creds-carvel
  template:
  - ytt:
      paths:
      - common/app-contents/postgres-as-a-service
      valuesFrom:
      - secretRef:
          name: tap-install-gitops
  deploy:
  - kapp: {}
