#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:data", "data")
---
#@ def config():
google:
  dns:
    config: #@ data.values.common.google.dns.config
    project_id: #@ data.values.common.google.dns.project_id
git:
  url: #@ data.values.common.git.url
  ref: #@ data.values.common.git.ref
  basic_auth_host: #@ data.values.common.repos.http.host
  basic_auth_username: #@ data.values.common.repos.http.basic_auth_username
  basic_auth_password: #@ data.values.common.repos.http.basic_auth_password
tap:
  ca: #@ data.values.common.ca
  cluster_name: #@ data.values.clusters.full.cluster_name
  tap_gui:
    auth:
      allow_guest_access: #@ data.values.clusters.full.tap_gui.allow_guest_access
  catalog: #@ data.values.clusters.full.catalog
  catalog_token: #@ data.values.clusters.full.catalog_token
  namespace: tap-install
  domains:
    base: #@ data.values.clusters.full.domain
    learningcenter: #@ "learningcenter." + data.values.clusters.full.domain
    tapGui: #@ "tap-gui." + data.values.clusters.full.domain
  credentials:
    #! Pick one registry for downloading images: Tanzu Network or Pivotal Network
    #! (use tanzuNet as key).
    tanzuNet: #! Host to fetch the package fron
      host: registry.tanzu.vmware.com
      username: #@ data.values.common.tap.tanzunet.username
      password: #@ data.values.common.tap.tanzunet.password
    registry:
      repositories: 
        buildService: tap/tbs
        ootbSupplyChain: tap/sc
      host: #@ data.values.common.tap.registry.host
      path: #@ data.values.common.tap.registry.path
      username: #@ data.values.common.tap.registry.username
      password: #@ data.values.common.tap.registry.password
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: tap-install-gitops
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-rule: "delete after deleting tap-install-gitops/app"
stringData:
  tap-secrets.yml: #@ yaml.encode(config())